export const SET_PRODUCTS_LIST = 'PRODUCT/SET_PRODUCTS_LIST';

export const SET_FAVORITES_LIST = 'FAVORITES/SET_FAVORITES_LIST';
export const ADD_TO_FAVORITES_LIST = 'FAVORITES/ADD_TO_FAVORITES_LIST';
export const REMOVE_FROM_FAVORITES_LIST = 'FAVORITES/REMOVE_FROM_FAVORITES_LIST';

export const SET_CART_LIST = 'CART/SET_CART_LIST';
export const ADD_PRODUCT_TO_CART = 'CART/ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'CART/REMOVE_PRODUCT_FROM_CART';

export const SET_OPEN_MODAL = 'MODAL/SET_OPEN_MODAL';
export const SET_CLOSE_MODAL = 'MODAL/SET_CLOSE_MODAL';

